var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(b){var c=function(){};c.prototype=b;return new c};$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},c={};try{return c.__proto__=b,c.a}catch(e){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,c){b.__proto__=c;if(b.__proto__!==c)throw new TypeError(b+" is not extensible");return b}:null;
$jscomp.inherits=function(b,c){b.prototype=$jscomp.objectCreate(c.prototype);b.prototype.constructor=b;if($jscomp.setPrototypeOf){var e=$jscomp.setPrototypeOf;e(b,c)}else for(e in c)if("prototype"!=e)if(Object.defineProperties){var a=Object.getOwnPropertyDescriptor(c,e);a&&Object.defineProperty(b,e,a)}else b[e]=c[e];b.superClass_=c.prototype};
var is_paused=!1,pointer_down=!1,cur_pointer,Game=function(){var b=Phaser.Scene.call(this,"game")||this;b.ready=!1;b.move_speed=90;b.key_down;b.player1;b.player2;b.anm_player1;b.anm_player2;b.ball;b.move_to;b.target_x=config.width/2;b.p1_anim_state="idle";b.p2_anim_state="idle";return b};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.update=function(){this.ready&&(this.anm_player1.setPosition(this.player1.x,this.player1.y),this.anm_player2.setPosition(this.player2.x,this.player2.y),pointer_down&&cur_pointer&&0==is_paused&&(this.player1.x<cur_pointer.x-20&&300<cur_pointer.y?"right"!=this.move_to&&"swing"!=this.p1_anim_state&&(this.p1_anim_state=this.move_to="right",this.anm_player1.anims.play("walk-right1")):this.player1.x>cur_pointer.x+20&&300<cur_pointer.y?"left"!=this.move_to&&"swing"!=this.p1_anim_state&&(this.p1_anim_state=
this.move_to="left",this.anm_player1.anims.play("walk-left1")):(this.move_to="","idle"!=this.p1_anim_state&&"swing"!=this.p1_anim_state&&(this.p1_anim_state="idle",this.anm_player1.anims.play("idle1"))),0>cur_pointer.x||720<cur_pointer.x||1080<cur_pointer.y)&&(this.move_to="",pointer_down=!1,"idle"!=this.p1_anim_state&&"swing"!=this.p1_anim_state&&(this.p1_anim_state="idle",this.anm_player1.anims.play("idle1"))),this.move_to&&("left"==this.move_to?40<this.player1.x&&(this.player1.x-=this.move_speed/
10):"right"==this.move_to&&this.player1.x<config.width-40&&(this.player1.x+=this.move_speed/10)),this.ball.y<config.height-300&&0==is_paused&&(this.player2.x<this.target_x?("right"!=this.p2_anim_state&&(this.p2_anim_state="right",this.anm_player2.anims.play("walk-right2",!0)),this.player2.x+=this.move_speed/10,this.player2.x>this.target_x&&(this.player2.x=this.target_x)):this.player2.x>this.target_x?("left"!=this.p2_anim_state&&(this.p2_anim_state="left",this.anm_player2.anims.play("walk-left2",!0)),
this.player2.x-=this.move_speed/10,this.player2.x<this.target_x&&(this.player2.x=this.target_x)):"idle"!=this.p2_anim_state&&(this.p2_anim_state="idle",this.anm_player2.anims.play("idle2",!0))))};
Game.prototype.create=function(){function b(b){"wait"==d&&150<b.y&&(d="play",n.setVisible(!1),a.ball.setVelocityY(h))}function c(){a.time.delayedCall(3E3,function(){"play"==d&&850>=h&&(h+=10);c()})}function e(){f>bestscore&&(bestscore=f);p.setText(f);f>=bestscore&&save_data(storage_key,bestscore)}var a=this,h=450,f=0,d="wait",t=this.add.group();this.add.sprite(config.width/2,config.height/2,"background");this.add.sprite(config.width/2,32,"bar");var u=this.add.sprite(120,55,"bar_score").setDepth(1),
v=this.add.sprite(310,55,"bar_bestscore").setDepth(1),p=this.add.text(120,65,f,{fontFamily:"vanilla",fontSize:26,align:"left",color:"#ffffff"}).setOrigin(.5).setDepth(1),w=this.add.text(310,65,bestscore,{fontFamily:"vanilla",fontSize:26,align:"left",color:"#ffffff"}).setOrigin(.5).setDepth(1),x=draw_button(645,55,"pause",a).setDepth(1);this.anims.create({key:"idle1",frames:this.anims.generateFrameNames("idle_player1"),frameRate:10,repeat:-1});this.anims.create({key:"idle2",frames:this.anims.generateFrameNames("idle_player2"),
frameRate:10,repeat:-1});this.anims.create({key:"swing1",frames:this.anims.generateFrameNames("swing_player1"),frameRate:20,repeat:0});this.anims.create({key:"swing2",frames:this.anims.generateFrameNames("swing_player2"),frameRate:20,repeat:0});this.anims.create({key:"walk-left1",frames:this.anims.generateFrameNames("walk_left_player1"),frameRate:18,repeat:-1});this.anims.create({key:"walk-right1",frames:this.anims.generateFrameNames("walk_right_player1"),frameRate:18,repeat:-1});this.anims.create({key:"walk-left2",
frames:this.anims.generateFrameNames("walk_left_player2"),frameRate:18,repeat:-1});this.anims.create({key:"walk-right2",frames:this.anims.generateFrameNames("walk_right_player2"),frameRate:18,repeat:-1});var n=this.add.sprite(config.width/2,700,"hand");n.setDepth(4);this.tweens.add({targets:n,scaleX:1.1,scaleY:1.1,duration:400,yoyo:!0,repeat:-1});this.player1=this.physics.add.sprite(config.width/2,810,"player1").setAlpha(0);var g=this.anm_player1=this.add.sprite(config.width/2,810,"idle_player1").setDepth(1);
g.anims.play("idle1",!0);this.player1.setCollideWorldBounds(!0);this.player1.body.setImmovable();var q=this.player1;this.player1.setBodySize(80,20,q);this.player2=this.physics.add.sprite(config.width/2,250,"player2").setAlpha(0);var k=this.anm_player2=this.add.sprite(config.width/2,250,"idle_player2");k.play("idle2",!0);this.player2.setCollideWorldBounds(!0);this.player2.body.setImmovable();var r=this.player2;this.player2.setBodySize(80,20,r);this.ball=this.physics.add.sprite(config.width/2,350,"ball");
this.ball.setCollideWorldBounds(!0);this.ball.setBounce(1);var l=this.ball;a.physics.add.collider(l,q,function(b,c){play_sound("ball1",a);f+=1;e();a.move_to="";"swing"!=a.p1_anim_state&&"play"==d&&(a.p1_anim_state="swing",g.anims.play("swing1"),a.target_x=Phaser.Math.Between(100,config.width-100),a.physics.moveTo(b,a.target_x,250,h));(function(){a.time.delayedCall(300,function(){"play"==d&&"swing"==a.p1_anim_state&&(a.p1_anim_state="idle",g.anims.play("idle1"))})})()},null,this);a.physics.add.collider(l,
r,function(b,c){play_sound("ball2",a);"play"==d&&(k.anims.play("swing2",!0),a.physics.moveTo(b,Phaser.Math.Between(100,config.width-100),config.height,h));(function(){a.time.delayedCall(300,function(){"play"==d&&k.anims.play("idle2",!0)})})()},null,this);this.input.keyboard.on("keydown",function(m){"wait"==d&&b({x:360,y:900});m=m.key;"ArrowLeft"==m&&"swing"!=a.p1_anim_state&&"play"==d&&"left"!=this.p1_anim_state&&(this.move_to=this.p1_anim_state="left",g.anims.play("walk-left1"));"ArrowRight"==m&&
"swing"!=a.p1_anim_state&&"play"==d&&"right"!=this.p1_anim_state&&(this.move_to=this.p1_anim_state="right",g.anims.play("walk-right1"))},this);this.input.keyboard.on("keyup",function(a){a=a.key;"ArrowLeft"==a&&"play"==d&&"left"==this.move_to&&"idle"!=this.p1_anim_state&&(this.move_to="",this.p1_anim_state="idle",g.anims.play("idle1"));"ArrowRight"==a&&"play"==d&&"right"==this.move_to&&"idle"!=this.p1_anim_state&&(this.move_to="",this.p1_anim_state="idle",g.anims.play("idle1"))},this);this.input.on("pointermove",
function(a){"play"==d&&pointer_down&&(cur_pointer=a)},this);this.input.on("pointerdown",function(a){"wait"==d&&b(a);"play"==d&&(pointer_down=!0)},this);this.input.on("pointerup",function(a){pointer_down=!1;this.move_to="";"play"==d&&"idle"!=this.p1_anim_state&&(this.p1_anim_state="idle",g.anims.play("idle1",!0))},this);this.ready=!0;this.input.on("gameobjectdown",function(b,c){c.button&&(play_sound("click",a),a.tweens.add({targets:c,scaleX:.95,scaleY:.95,yoyo:!0,duration:100,ease:"Linear",onComplete:function(){if("play"===
d){if("pause"===c.name){d="paused";is_paused=!0;a.anims.pauseAll();a.physics.pause();a.move_to="";u.setDepth(0);v.setDepth(0);x.setDepth(0);p.setDepth(0);w.setDepth(0);g.setDepth(0);var b=a.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);b.setInteractive();b.alpha=0;a.tweens.add({targets:b,alpha:.5,duration:200});var e=a.add.sprite(360,540,"popup_paused"),m=draw_button(525,365,"close",a),f=draw_button(360,500,"resume",a),h=draw_button(235,650,"restart",a),l=draw_button(360,650,"menu",
a),k=draw_button(485,650,"sound_on",a);check_audio(k);t.addMultiple([b,e,m,f,h,l,k])}}else if("resume"===c.name||"close"===c.name)if(d="play",is_paused=!1,t.clear(!0,!0),a.anims.resumeAll(),a.physics.resume(),"right"==a.p1_anim_state||"left"==a.p1_anim_state)a.p1_anim_state="idle",g.anims.play("idle1");"sound"===c.name?switch_audio(c):"restart"===c.name?(is_paused=!1,a.target_x=config.width/2,a.anims.resumeAll(),show_ad(),a.scene.restart()):"menu"===c.name&&(is_paused=!1,a.target_x=config.width/2,
a.anims.resumeAll(),show_ad(),a.scene.start("menu"))}}))},this);a.time.addEvent({delay:10,loop:!0,callback:function(){if("play"==d)if(10>=l.y)play_sound("completed",a),f+=10,e(),"play"==d&&(a.p1_anim_state="idle",a.p2_anim_state="idle",a.move_to="",pointer_down=!1,a.target_x=config.width/2,q.setPosition(config.width/2,790),r.setPosition(config.width/2,230),l.setPosition(config.width/2,250),a.ball.setVelocity(0,h),g.anims.play("idle1"),k.anims.play("idle2"));else if(1065<=l.y){d="gameover";play_sound("gameover",
a);is_paused=!0;a.move_to="";a.anims.pauseAll();a.physics.pause();u.setDepth(0);v.setDepth(0);x.setDepth(0);p.setDepth(0);w.setDepth(0);g.setDepth(0);submit_score(f);f>=bestscore&&save_data(storage_key,bestscore);var b=a.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);b.setInteractive();b.alpha=0;a.tweens.add({targets:b,alpha:.5,duration:200});a.add.sprite(360,540,"popup_gameover");a.add.text(425,455,f,{fontFamily:"vanilla",fontSize:30,align:"left",color:"#ffffff"}).setOrigin(.5);a.add.text(425,
525,bestscore,{fontFamily:"vanilla",fontSize:30,align:"left",color:"#ffffff"}).setOrigin(.5);draw_button(235,650,"restart",a);draw_button(360,650,"menu",a);b=draw_button(485,650,"sound_on",a);check_audio(b)}}});c()};var config={type:Phaser.AUTO,width:720,height:1080,physics:{default:"arcade",arcade:{debug:!1}},scale:{mode:Phaser.Scale.FIT,parent:"game_content",autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,Load,Menu,Game]},game=new Phaser.Game(config);
